name: Build contracts
on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18"]
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn install --check-cache

      - name: Yarn build
        run: yarn build

      - name: Lint
        run: yarn lint
